server:
  port: 9876
  shutdown: graceful
  servlet:
    context-path: /ytora
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  aop:
    proxy-target-class: true
  # 开启虚拟线程：接收请求的线程和 @Async 异步方法使用的线程会默认使用虚拟线程
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
knife4j:
  production: false
  enable: true
  setting:
    language: zh_cn
springdoc:
  override-with-generic-response: false
logging:
  config: classpath:log/logback-dev.xml
ytora:
  name: @project.name@
  version: @revision@
  # 基础路径
  base-package: xyz.ytora.**
  # SSE实时推送是否开启
  sse: off
  # 授权认证
  auth:
    enable: true
    token-invalid-time: 6000
    allow-credentials: true
    origins: http://localhost:8765
  # 缓存设置
  cache:
    default-cache: local
    impl:
      local: xyz.ytora.base.cache.support.local.CacheByLocal
      redis: xyz.ytora.base.cache.support.redis.CacheByRedis
      db: xyz.ytora.base.cache.support.db.CacheByDb
  # 存储设置
  storage:
    type: xyz.ytora.base.storage.support.LocalFileStorageServiceImpl
    strategy: xyz.ytora.base.storage.strategy.Murmur3_128StrategyImpl
    max: 100MB
    path: "file-storage/"
  # sqlux设置
  sqlux:
    # 主数据源
    primary-key: primary
    # 慢SQL阈值
    slow-sql-threshold: 5000
    # SQL日志打印器
    sql-logger-impl: xyz.ytora.base.sqlux.log.Slf4jSqlLogger
    # 是否开启自动建表功能（当实体类对应的数据库表不存在时）
    auto-create-table: true
    # 实体类路径
    entity-path: xyz.ytora.core.**.entity.*
    # 数据源信息
    dynamic-ds:
      primary:
        desc: '主业务库'
        url: jdbc:postgresql://localhost:5432/ytora?currentSchema=ytora&ssl=false&stringtype=unspecified
        username: admin
        password: 220600
        driver-class-name: org.postgresql.Driver
        type: com.zaxxer.hikari.HikariDataSource
#      test:
#        desc: '测试库'
#        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public&ssl=false&stringtype=unspecified
#        username: admin
#        password: 220600
#        driver-class-name: org.postgresql.Driver
#        type: com.zaxxer.hikari.HikariDataSource